### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by offbeatshotz** [norge420/hurri-artic-bot-script#1]
Traceback (most recent call last):
  File "src/run.py", line 1, in <module>
    from bot import Bot
  File "C:\Users\norsk\Downloads\botty source d2r botting\botty-0.2.2 source\botty_v0.2.2\src\bot.py", line 3, in <module>
    from char.hammerdin import Hammerdin
  File "C:\Users\norsk\Downloads\botty source d2r botting\botty-0.2.2 source\botty_v0.2.2\src\char\hammerdin.py", line 3, in <module>
    from char.i_char import IChar
  File "C:\Users\norsk\Downloads\botty source d2r botting\botty-0.2.2 source\botty_v0.2.2\src\char\i_char.py", line 3, in <module>
    from template_finder import TemplateFinder
  File "C:\Users\norsk\Downloads\botty source d2r botting\botty-0.2.2 source\botty_v0.2.2\src\template_finder.py", line 3, in <module>
    from screen import Screen
  File "C:\Users\norsk\Downloads\botty source d2r botting\botty-0.2.2 source\botty_v0.2.2\src\screen.py", line 8, in <module>
    from config import Config
  File "C:\Users\norsk\Downloads\botty source d2r botting\botty-0.2.2 source\botty_v0.2.2\src\config.py", line 74
    self.hammerdin = self._config["hammerdin"])
                                              ^
SyntaxError: unmatched ')'

**Comment by offbeatshotz** [comment]
source files in repo
can not fix errors when building
